# Generated by Django 3.1.7 on 2021-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.IntegerField(null=True)),
                ('old_price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'urls',
                'managed': False,
            },
        ),
    ]
