# Generated by Django 3.1.7 on 2021-04-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'managed': False, 'ordering': ['date', 'id'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='urls',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
