# Generated by Django 3.1.7 on 2021-04-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_auto_20210401_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ['id'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
