# Generated by Django 3.1.7 on 2021-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_auto_20210402_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='product_photo',
            field=models.ImageField(default='/home/igor/igor/projects/parser/price_parser/mediadefault.png', height_field=250, upload_to='product', width_field=250),
        ),
    ]
