# Generated by Django 3.1.7 on 2021-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_urls_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='product_photo',
            field=models.ImageField(default='/home/igor/igor/projects/parser/price_parser/media/default.png', height_field=250, upload_to='product', width_field=250),
        ),
    ]
