# Generated by Django 3.1.7 on 2021-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_auto_20210402_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='product_photo',
            field=models.ImageField(default='/home/igor/igor/projects/parser/price_parser/media/default.png', upload_to='product'),
        ),
    ]
