# Generated by Django 3.1.7 on 2021-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_auto_20210402_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='product_photo',
            field=models.ImageField(default='default.png', upload_to='product'),
        ),
    ]
