# Generated by Django 3.1.7 on 2021-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_auto_20210402_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='name',
            field=models.CharField(default='Undefiend name', max_length=255),
        ),
    ]
