# Generated by Django 3.1.7 on 2021-04-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_urls_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='urls',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
