# Generated by Django 3.1.7 on 2021-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_auto_20210404_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
